### Introduction to SQL Sub-Queries

This notebook explore the basics of the use of sub-queries with SQL

First we will read the cvs file from our github repository.

In [1]:
import pandas as pd

Introduction to Social Media Users Dataset

The Social Media Users Dataset is a comprehensive collection of data that provides insights into the behaviors, interests, and demographic information of social media users worldwide. This dataset contains valuable information such as user IDs, names, gender, date of birth (DOB), interests, cities, and countries. By analyzing this dataset, we can explore various trends and patterns, such as the relationship between interests and demographics, the influence of location on user behavior, and how different factors (like age and gender) shape social media usage.

The data has been processed and analyzed using SQL for querying and Google Colab for Python-based analysis, making it possible to draw meaningful conclusions about user behavior across different countries and interest categories. The insights derived from this dataset can be used for various applications, such as targeted marketing, user behavior prediction, and regional trend analysis.

This dataset serves as a powerful resource for understanding how users engage with social media and the topics they care about, providing valuable insights for businesses, researchers, and data enthusiasts.

In [2]:
! git clone https://github.com/MhmtAkbba/Social-Media.git

Cloning into 'Social-Media'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), 2.85 MiB | 3.79 MiB/s, done.

The code you've provided is intended to load a CSV file into a Pandas DataFram

In [3]:
df = pd.read_csv("/content/Social-Media/SocialMediaUsersDataset.csv")

In [4]:
df.keys()

Index(['UserID', 'Name', 'Gender', 'DOB', 'Interests', 'City', 'Country'], dtype='object')

In [5]:
df

,UserID,Name,Gender,DOB,Interests,City,Country
0,1,Jesse Lawhorn,Female,1958-10-15,"'Movies', 'Fashion', 'Fashion', 'Books'",Sibolga,Indonesia
1,2,Stacy Payne,Female,2004-07-21,"'Gaming', 'Finance and investments', 'Outdoor ...",Al Abyār,Libya
2,3,Katrina Nicewander,Female,2000-02-07,"'DIY and crafts', 'Music', 'Science', 'Fashion'",Wādī as Sīr,Jordan
3,4,Eric Yarbrough,Male,1985-04-14,"'Outdoor activities', 'Cars and automobiles'",Matera,Italy
4,5,Daniel Adkins,Female,1955-09-18,"'Politics', 'History'",Biruaca,Venezuela
...,...,...,...,...,...,...,...
99995,99996,Lionel Denault,Female,1983-07-31,'DIY and crafts',Dawan,China
99996,99997,Margie Mieszala,Female,1954-05-20,"'Cars and automobiles', 'Cooking', 'Outdoor ac...",Arcos de la Frontera,Spain
99997,99998,Joan Mercedes,Male,1975-06-06,"'Business and entrepreneurship', 'Cooking'",Los Andes,Chile
99998,99999,Marvin Massa,Female,1959-11-16,"'Gaming', 'Business and entrepreneurship', 'Fa...",Varjota,Brazil
99999,100000,Josh Young,Female,1988-07-29,"'Politics', 'Pets'",Brzeg,Poland

Data Normailization

Data normalization is the process of organizing data in a database to reduce redundancy and improve data integrity by structuring tables and establishing relationships according to specific rules.
Here's a more detailed explanation:
Purpose:
The primary goal of data normalization is to eliminate redundancy and ensure data consistency, making it easier to manage and query the database

In [6]:
# Step 1: Clean 'Interests' column (convert string into list)
df["Interests"] = df["Interests"].apply(lambda x: [i.strip().strip("'") for i in x.split(",")])

In [7]:

# Step 2: Explode the 'Interests' column to get one row per interest
df = df.explode("Interests")

In [8]:
df

,UserID,Name,Gender,DOB,Interests,City,Country
0,1,Jesse Lawhorn,Female,1958-10-15,Movies,Sibolga,Indonesia
0,1,Jesse Lawhorn,Female,1958-10-15,Fashion,Sibolga,Indonesia
0,1,Jesse Lawhorn,Female,1958-10-15,Fashion,Sibolga,Indonesia
0,1,Jesse Lawhorn,Female,1958-10-15,Books,Sibolga,Indonesia
1,2,Stacy Payne,Female,2004-07-21,Gaming,Al Abyār,Libya
...,...,...,...,...,...,...,...
99998,99999,Marvin Massa,Female,1959-11-16,Fashion,Varjota,Brazil
99998,99999,Marvin Massa,Female,1959-11-16,Parenting and family,Varjota,Brazil
99998,99999,Marvin Massa,Female,1959-11-16,Photography,Varjota,Brazil
99999,100000,Josh Young,Female,1988-07-29,Politics,Brzeg,Poland
99999,100000,Josh Young,Female,1988-07-29,Pets,Brzeg,Poland

The code you've provided creates an SQLite database table named Social if it doesn't already exist.

In [9]:
# CREATING THE TABLE
import sqlite3

conn = sqlite3.connect('Social.db')
print("Opened database successfully");

conn.execute('''
CREATE TABLE IF NOT EXISTS Social(UserID INTEGER,
                      Name text,
                      Gender text,
                      DOB date, Interests Text, City text, Country text);''')

conn.commit()

print("Table created successfully");

Opened database successfully
Table created successfully

The code you've written loops through a Pandas DataFrame and inserts each row into an SQLite database.

In [10]:
# Loop through the DataFrame and insert each row into the database
for index, row in df.iterrows():
    conn.execute('''
        INSERT INTO Social (
            UserID, Name, Gender, DOB, Interests, City, Country
        ) VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', (
        int(row['UserID']),  # UserID (Integer)
        row['Name'],         # Name (Text)
        row['Gender'],       # Gender (Text)
        row['DOB'],          # DOB (Date)
        row['Interests'],    # Interests (Text)
        row['City'],         # City (Text)
        row['Country']       # Country (Text)
    ))

# Commit the transaction to save all changes
conn.commit()

This analysis examines the distribution of interests across different countries and identifies how many users have each interest in those countries.

This analysis allows us to see how different interests are distributed across various countries.

It provides valuable insights into which countries are more engaged with specific interests, helping to inform marketing strategies or international studies.

By sorting by User_Count, we can identify popular interests that have a high number of users in specific countries.

In [12]:
pd.read_sql_query('''SELECT  Interests, Country, COUNT(*) AS User_Count
FROM Social
GROUP BY Interests, Country
ORDER BY Interests, User_Count DESC;''', conn)

     Interests                             Country  User_Count
0          Art                       United States        1174
1          Art                               India         954
2          Art                               China         754
3          Art                              Brazil         473
4          Art                              Russia         412
...        ...                                 ...         ...
5638    Travel                          Cabo Verde           1
5639    Travel  Bonaire, Saint Eustatius and Saba            1
5640    Travel                               Aruba           1
5641    Travel                             Andorra           1
5642    Travel                       Aland Islands           1

[5643 rows x 3 columns]

This analysis identifies the number of users with an interest in Science across different countries.

This analysis helps us understand which countries have the most users interested in Science.

It provides insights that can be useful for research, education, and targeted content creation related to scientific topics.

By sorting the results, we can identify the global distribution of science interest and focus on countries where science engagement is most prominent.

In [13]:
pd.read_sql_query('''SELECT Country, COUNT(*) AS Science_User_Count
FROM Social
WHERE Interests LIKE '%Science%'
GROUP BY Country
ORDER BY Science_User_Count DESC;''', conn)

            Country  Science_User_Count
0     United States                1200
1             India                 927
2             China                 722
3            Brazil                 464
4           Germany                 414
..              ...                 ...
184          Belize                   1
185        Barbados                   1
186           Aruba                   1
187        Anguilla                   1
188  American Samoa                   1

[189 rows x 2 columns]

This analysis identifies individuals born between 1950 and 1980 who have an interest in Fashion.

This analysis helps us identify individuals within a specific age group who are interested in Fashion.

By sorting alphabetically, it allows for easy comparison of Fashion interest across users in different countries.

It can be useful for targeting specific marketing campaigns or understanding fashion preferences across different age groups.

In [14]:
pd.read_sql_query('''SELECT Name, Country,  Interests
FROM Social
WHERE DOB BETWEEN '1950-01-01' AND '1980-12-31'
AND Interests LIKE '%Fashion%'
ORDER BY Name ASC;''', conn)

                    Name         Country Interests
0         Aaron Almaguer   United States   Fashion
1           Aaron Barnes         Algeria   Fashion
2          Aaron Bullock           Italy   Fashion
3          Aaron Burkman          Brazil   Fashion
4            Aaron Davis          Brazil   Fashion
...                  ...             ...       ...
10607     Zachary Wolery          Canada   Fashion
10608        Zane Turner     Philippines   Fashion
10609  Zenaida Shininger          Brazil   Fashion
10610         Zofia Reed  United Kingdom   Fashion
10611        Zona Bailey        Malaysia   Fashion

[10612 rows x 3 columns]

This analysis focuses on the interests of users from Canada.

This analysis helps us understand the range of interests that Canadian users have and the distribution of these interests across names.

By sorting alphabetically, we can compare interests across different individuals in Canada and identify any patterns or trends.

This could be useful for targeted marketing, research, or content curation for Canadian audiences.

In [15]:
pd.read_sql_query('''SELECT Name, Interests
FROM Social
WHERE Country = 'Canada'
ORDER BY Name ASC, Interests ASC;''', conn)

                  Name                   Interests
0      Abraham Mckemie                     Fitness
1      Abraham Mckemie                   Gardening
2     Abram Brakefield                      Gaming
3     Abram Brakefield                      Nature
4     Abram Brakefield          Outdoor activities
...                ...                         ...
3583    Zachary Wolery  Social causes and activism
3584    Zachery Lester     Finance and investments
3585    Zachery Lester                     Fitness
3586    Zachery Lester                       Music
3587    Zachery Lester                      Nature

[3588 rows x 2 columns]

This analysis examines the interests of users from Italy.

This analysis helps us understand the diversity of interests among users in Italy.

It can be useful for market research, identifying trends, and targeting content or products to Italian audiences based on their interests.

By sorting the interests alphabetically, we can more easily identify popular or niche interests in the region.

In [16]:
pd.read_sql_query('''SELECT Interests, COUNT(*) AS Interest_Count
FROM Social
WHERE Country = 'Italy'
GROUP BY Interests
ORDER BY Interests ASC;''', conn)

                        Interests  Interest_Count
0                             Art             227
1                          Beauty             223
2                           Books             224
3   Business and entrepreneurship             246
4            Cars and automobiles             221
5                         Cooking             244
6                  DIY and crafts             236
7          Education and learning             225
8                         Fashion             430
9         Finance and investments             231
10                        Fitness             238
11                Food and dining             215
12                         Gaming             221
13                      Gardening             247
14            Health and wellness             240
15                        History             222
16                         Movies             247
17                          Music             250
18                         Nature             212
19             Outdoor activities             242
20           Parenting and family             239
21                           Pets             235
22                    Photography             237
23                       Politics             204
24                        Science             222
25     Social causes and activism             231
26                         Sports             258
27                     Technology             235
28                         Travel             221

This analysis identifies female users who have interests in Politics or History.

This analysis helps us identify female individuals with a particular interest in political or historical topics.

It can be useful for targeting campaigns, social studies, or understanding gender-based preferences in certain subject areas.

By sorting by name, it allows for easy reference and follow-up for deeper analysis or research.

In [17]:
pd.read_sql_query('''SELECT Name, Country
FROM Social
WHERE Gender = 'Female'
AND (Interests LIKE '%Politics%' OR Interests LIKE '%History%')
ORDER BY Name ASC;''' , conn)

                 Name                Country
0         Aaron Albus                 Brazil
1     Aaron Archuleta                Nigeria
2       Aaron Barrett             Azerbaijan
3        Aaron Divine              Venezuela
4        Aaron Fisher              Australia
...               ...                    ...
9755     Zella Hauser                Tunisia
9756     Zelma Parker          United States
9757     Zetta Chavez                  India
9758      Zoe Trevino  Republic of the Congo
9759        Zora Wood                 Mexico

[9760 rows x 2 columns]

In [18]:
pd.read_sql_query('''SELECT Country, COUNT(*) AS Outdoor_Activity_Count
FROM Social
WHERE Interests LIKE '%Outdoor%'
GROUP BY Country
ORDER BY Outdoor_Activity_Count DESC;''' , conn)

                                Country  Outdoor_Activity_Count
0                         United States                    1209
1                                 India                     967
2                                 China                     730
3                                Brazil                     479
4                                Russia                     423
..                                  ...                     ...
185                   Equatorial Guinea                       1
186                             Curacao                       1
187                        Cook Islands                       1
188                       Cocos Islands                       1
189  Bonaire, Saint Eustatius and Saba                        1

[190 rows x 2 columns]

This analysis identifies common interests between users from Canada and China.

his analysis helps us understand cultural similarities between Canada and China in terms of interests.

It can be valuable for international businesses, social research, and trend analysis.

By identifying shared interests, companies can develop strategies that appeal to both markets.

In [19]:
pd.read_sql_query('''SELECT Interests, COUNT(*) AS Total_Users
FROM (
    SELECT
        UserID,
       Interests,
        Country
    FROM social
) sub
WHERE Country IN ('Canada', 'China')
GROUP BY Interests
HAVING COUNT(DISTINCT Country) = 2 -- İlgi alanının her iki ülkede de olması gerekiyor
ORDER BY Total_Users DESC;''', conn)

                        Interests  Total_Users
0                         Fashion         1695
1                            Pets          922
2      Social causes and activism          904
3                          Gaming          904
4                          Travel          903
5                         Fitness          901
6                         Cooking          897
7         Finance and investments          892
8                  DIY and crafts          880
9                          Movies          879
10                          Books          878
11         Education and learning          875
12                            Art          875
13                    Photography          867
14                        History          867
15                Food and dining          860
16                       Politics          854
17                        Science          849
18                     Technology          846
19  Business and entrepreneurship          843
20                      Gardening          839
21                         Beauty          839
22                          Music          837
23             Outdoor activities          834
24                         Nature          826
25                         Sports          805
26           Cars and automobiles          803
27            Health and wellness          796
28           Parenting and family          773

This analysis focuses on the popularity of the interest in "Pets" across different countries.

This analysis helps us understand which countries have the most interest in pets.

It can be useful for pet-related businesses, market research, and cultural studies.

By comparing different countries, we can see where pet ownership and pet-related activities are more popular.

In [23]:
pd.read_sql_query('''SELECT
    Country,
    COUNT(*) AS Pets_Interest_Count
FROM social
WHERE Interests = 'Pets'
GROUP BY Country
ORDER BY Pets_Interest_Count DESC;''', conn)

            Country  Pets_Interest_Count
0     United States                 1246
1             India                  991
2             China                  794
3            Brazil                  465
4           Germany                  448
..              ...                  ...
188        Dominica                    1
189         Comoros                    1
190   Cocos Islands                    1
191         Bermuda                    1
192  American Samoa                    1

[193 rows x 2 columns]

This analysis examines how interests vary across different countries.

This analysis helps us understand cultural and regional differences in interests.

It can be useful for targeted marketing, business expansion, and social research by identifying which hobbies or activities are more popular in specific countries.

By comparing interest trends across countries, we can see how location influences people's preferences.

In [25]:
pd.read_sql_query('''SELECT
    Country,
    Interests,
    COUNT(*) AS Interest_Count
FROM social
GROUP BY Country, Interests
ORDER BY Country, Interest_Count DESC;''', conn)

          Country                      Interests  Interest_Count
0     Afghanistan                        Fashion              30
1     Afghanistan                         Sports              26
2     Afghanistan  Business and entrepreneurship              26
3     Afghanistan                           Pets              25
4     Afghanistan                      Gardening              25
...           ...                            ...             ...
5638     Zimbabwe                          Music               9
5639     Zimbabwe                         Movies               9
5640     Zimbabwe                         Gaming               9
5641     Zimbabwe                         Beauty               8
5642     Zimbabwe                        Science               5

[5643 rows x 3 columns]

This analysis focuses on the interests of people born after 1990.

This analysis helps us understand generational trends in hobbies and interests.

It provides insights into what younger individuals are more engaged with, which
can be useful for marketing, product development, and social research.

By comparing it with older age groups, we can analyze how interests have changed over time.

In [20]:
pd.read_sql_query('''SELECT Interests, COUNT(*) AS Interest_Count
FROM Social
WHERE DOB > 1990
GROUP BY Interests
ORDER BY Interest_Count DESC;''', conn)

                        Interests  Interest_Count
0                         Fashion           20077
1                            Pets           10164
2                         Cooking           10163
3                         Fitness           10108
4                          Movies           10102
5                          Gaming           10093
6                          Travel           10048
7            Cars and automobiles           10048
8              Outdoor activities           10041
9                           Books           10029
10        Finance and investments           10021
11  Business and entrepreneurship           10020
12                    Photography           10001
13                            Art            9985
14     Social causes and activism            9966
15            Health and wellness            9953
16                      Gardening            9946
17                     Technology            9938
18                         Sports            9923
19         Education and learning            9923
20                         Nature            9913
21                        History            9899
22           Parenting and family            9898
23                          Music            9887
24                Food and dining            9886
25                 DIY and crafts            9872
26                         Beauty            9858
27                        Science            9792
28                       Politics            9731